In [2]:
import numpy as np
array = np.arange(7) 
print(array)
# using numpy.array_split() method 
gfg = np.array_split(array, 4) 

[0 1 2 3 4 5]


In [3]:
print(gfg)

[array([0, 1]), array([2, 3]), array([4]), array([5])]


In [5]:
for i in array:
    print(i)

0
1
2
3
4
5


In [18]:
X_a = np.concatenate(gfg[0:3])
X_b = np.concatenate(gfg[3:])

In [19]:
print(X_a)
print(X_b)

[0 1 2 3 4]
[5]


In [20]:
print(np.concatenate((X_a, X_b)))

[0 1 2 3 4 5]
